name: alpondith_web
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter: 
    sdk: flutter
  font_awesome_flutter: ^9.2.0
  url_launcher: ^6.0.17

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  fonts:
    - family: Inconsolota
      fonts:
        - asset: fonts/Inconsolata-Regular.ttf
          weight: 300
        - asset: fonts/Inconsolata-Bold.ttf
          weight: 700

